esphome:
  comment: >
    ESPHome software for generic smartplugs with power meters.
    Works with Gosund SP111 and BlitzWolf® BW-SHP6 Pro 15A.
  project:
    name: "sowitech.generic_smartplug"
    version: "1.0"

esp8266:
  board: esp8285
  restore_from_flash: true

packages:
  smartplug_generic: !include
    file: device.smartplug.base.yaml
    vars:
      # Device settings and overrides
      current_res: 0.00117
      voltage_div: 755
      max_power: 3450
      # Device pinout
      red_led: GPIO0
      blue_led: GPIO2
      cf1_pin: GPIO4
      cf_pin: GPIO5
      sel_pin: GPIO12
      button_pin: GPIO13
      relay_pin: GPIO15
