packages:
  base_min: !include device.base.min.yaml
  mqtt: !include
    file: packages/mqtt.yaml
    vars:
      mqtt_topic_prefix: esphome/${device_name}
  button_shutdown: !include
    file: components/general.config-button.yaml
    vars:
      platform: shutdown
      name: Shutdown
      class: ""

binary_sensor:
  - platform: status
    name: Status
    entity_category: diagnostic

text_sensor:
  - platform: version
    name: "${device_name} ESPHome Version"
    entity_category: diagnostic
  - platform: wifi_info
    bssid:
      name: "${device_name} BSSID"
      entity_category: diagnostic
      disabled_by_default: true
    scan_results:
      name: "${device_name} Scan Results"
      entity_category: diagnostic
      disabled_by_default: true
    dns_address:
      name: "${device_name} DNS Address"
      entity_category: diagnostic
      disabled_by_default: true
