esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}
  on_boot:
    priority: -10
    then:
      - light.turn_on: blue_led_light

esp8266:
  board: esp01_1m

packages:
  base: !include device.base.yaml
  logger_off: !include settings.uart-logger-off.yaml

output:
  # Register the blue LED as a dimmable output....
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # ...and then make a light out of it.
  - platform: monochromatic
    id: blue_led_light
    name: Status LED
    output: blue_led
    internal: true
