esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}
  on_boot:
    priority: -10
    then:
      - light.turn_on: blue_light

esp8266:
  board: esp01_1m

packages:
  base: !include device.base.yaml
  logger_off: !include settings.uart-logger-off.yaml

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: button_toggle
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1
  - platform: gpio
    name: Switch
    pin: GPIO04
    id: switch_input
    on_press:
      then:
        - switch.toggle:
            id: relay_1
    on_release:
      then:
        - switch.toggle:
            id: relay_1

switch:
  - platform: gpio
    name: Relay
    pin: GPIO12
    id: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  - platform: monochromatic
    id: blue_light
    name: Blue LED
    output: blue_led
    internal: true
