esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

esp8266:
  board: esp01_1m
  restore_from_flash: true

packages:
  base: !include device.base.yaml
  logger_off: !include components/logger.disabled-uart.yaml
  status_led: !include
    file: components/esp8266-pwm.status-led.yaml
    vars:
      led_pin: GPIO13
      control_id: status_led_light
  multifunction_button: !include
    file: components/button.multifunction.yaml
    vars:
      button_pin: GPIO00
      relay_id: relay

binary_sensor:
  - platform: gpio
    name: Switch
    pin: GPIO04
    id: switch_input
    entity_category: diagnostic
    on_state:
      then:
        - switch.toggle:
            id: relay

switch:
  - platform: gpio
    name: Relay
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
