esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

esp8266:
  board: esp01_1m

packages:
  base: !include device.base.yaml
  logger_off: !include settings.uart-logger-off.yaml
  status_led: !include
    file: components/pwm.status-led.yaml
    vars:
      led_pin: GPIO13
      control_id: status_led_light
  night_mode: !include
    file: components/template.night-mode.yaml
    vars:
      control_id: status_led_light
      off_value: 20%
      on_value: 100%
  multifunction_button: !include
    file: components/button.multifunction.yaml
    vars:
      button_pin: GPIO00
      relay_id: relay

binary_sensor:
  - platform: gpio
    name: Switch
    pin: GPIO04
    id: switch_input
    entity_category: diagnostic
    on_state:
      then:
        - switch.toggle:
            id: relay

switch:
  - platform: gpio
    name: Relay
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
