esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}
  on_boot:
    priority: -10
    then:
      - switch.turn_on: relay
      - output.turn_on: led

esp8266:
  board: esp8285

packages:
  base: !include device.base.yaml
  logger_off: !include settings.uart-logger-off.yaml
  hass_time: !include components/general.hass-time.yaml

# Button configuration
binary_sensor:
  - platform: gpio
    name: Toggle Button
    id: button
    pin:
      number: ${button_pin}
      inverted: true
    on_press:
      then:
        - switch.toggle: relay

# Setup of LED's used in displaying Switch status
output:
  - platform: gpio
    pin: ${red_led}
    inverted: true
    id: led

# Config for switch
switch:
  - platform: gpio
    pin: ${relay_pin}
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    name: Relay
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

# Status LED for connection
status_led:
  pin:
    number: ${blue_led}
    inverted: true

# Sensors for Voltage (V), Current (A), Power (W), Daily energy usage (kWh)
sensor:
  - platform: hlw8012
    id: power_meter
    sel_pin:
      number: ${sel_pin}
      inverted: true
    cf_pin: ${cf_pin}
    cf1_pin: ${cf1_pin}
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s
    current:
      name: Current
      id: current
      unit_of_measurement: A
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: Voltage
      id: voltage
      unit_of_measurement: V
      accuracy_decimals: 1
      icon: mdi:flash-outline
    energy:
      name: Energy
      unit_of_measurement: Wh
      icon: mdi:flash-outline
    power:
      name: Power
      id: power
      unit_of_measurement: W
      accuracy_decimals: 0
      icon: mdi:flash-outline
      on_value_range:
          above: ${max_power}
          then:
            - output.turn_off: led
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: Switch turned off because power exceeded ${max_power}W
  - platform: total_daily_energy
    name: Daily Energy
    power_id: power
    unit_of_measurement: kWh
    accuracy_decimals: 5
    filters:
      - multiply: 0.001
