# WIP! Do not use!

esphome:
  comment: >
    ESPHome software for Aubess switches with power meters.
  project:
    name: "sowitech.aubess_meterswitch"
    version: "indev"

## Notes
# https://community.home-assistant.io/t/cheap-tuya-smart-switch-em/453647/9
# https://github.com/tuya-cloudcutter/tuya-cloudcutter
# https://esphome.io/components/sensor/bl0942.html
# https://esphome.io/components/libretiny
# https://docs.libretiny.eu/boards/wb2s/
# https://templates.blakadder.com/aubess_power_monitor_switch.html
# https://www.elektroda.com/rtvforum/topic3912748.html
# https://www.elektroda.com/rtvforum/topic3980879.html
# https://www.elektroda.com/rtvforum/topic4006384.html

bk72xx:
  board: wb2s
  restore_from_flash: true

packages:
  base: !include device.base.min.yaml
  logger_off: !include components/logger.disabled-uart.yaml
  hass_time: !include components/general.hass-time.yaml
  multifunction_button: !include
    file: components/button.multifunction.yaml
    vars:
      button_pin: ${button_pin}
      relay_id: relay

# Config for the relay
switch:
  - platform: gpio
    pin: ${relay_pin}
    restore_mode: RESTORE_DEFAULT_ON
    id: relay
    name: Relay
    device_class: outlet

# Sensors for Voltage (V), Current (A), Power (W), Daily energy usage (kWh)
sensor:
  - platform: hlw8012
    id: power_meter
    sel_pin:
      number: ${sel_pin}
      inverted: true
    cf_pin: ${cf_pin}
    cf1_pin: ${cf1_pin}
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s
    current:
      name: Current
      id: current
      device_class: current
      accuracy_decimals: 3
    voltage:
      name: Voltage
      id: voltage
      device_class: voltage
      accuracy_decimals: 1
    energy:
      name: Energy
      device_class: energy
    power:
      name: Power
      id: power
      device_class: power
      accuracy_decimals: 0
      on_value_range:
          above: ${max_power}
          then:
            - output.turn_off: indicator_led
            - switch.turn_off: relay
            - logger.log:
                format: Safety trigger fired for ${device_name}! Power exceeded the maximum of ${max_power}W.
                level: ERROR
  - platform: total_daily_energy
    name: Daily Energy
    id: daily_energy
    power_id: power
    device_class: power
    accuracy_decimals: 5
    filters:
      - multiply: 0.001
