esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  area: ${area}

esp8266:
  board: esp01_1m

packages:
  base: !include device.base.yaml
  logger_off: !include settings.uart-logger-off.yaml
  status_led: !include
    file: components/pwm.status-led.yaml
    vars:
      led_pin: GPIO13
      control_id: status_led_light
  night_mode: !include
    file: components/template.night-mode.yaml
    vars:
      control_id: status_led_light
      off_value: 20%
      on_value: 100%
