# A sample settings file.
#
# You can copy this file as settings.yaml and use your own values.
# Alternatively settings.yaml can be empty. The only requirement is for it to
# exist.

wifi:
  manual_ip:
    static_ip: 192.168.1.${device_id}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 1.1.1.1
    dns2: 9.9.9.9
  domain: ".local"
